ALTER TABLE player_progress
  ADD COLUMN IF NOT EXISTS necro_attack_bonus INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS necro_defense_bonus INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS necro_bonus_games INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS necro_summon_effect JSONB NULL;
