-- Translate special effects to Russian
UPDATE items SET special_effect = 'Ярость' WHERE special_effect = 'rage';
UPDATE items SET special_effect = 'Крепость' WHERE special_effect = 'fortress';
UPDATE items SET special_effect = 'Уникальные криты' WHERE special_effect = 'unrepeated_crit';
UPDATE items SET special_effect = 'Древний вампиризм' WHERE special_effect = 'ancient_lifesteal';
UPDATE items SET special_effect = 'Усиление заклинаний' WHERE special_effect = 'spell_amplification';
UPDATE items SET special_effect = 'Мастерство последовательностей' WHERE special_effect = 'sequence_mastery';
UPDATE items SET special_effect = 'Хаос ИИ' WHERE special_effect = 'ai_chaos';
UPDATE items SET special_effect = 'Призыв' WHERE special_effect = 'summon';
UPDATE items SET special_effect = '-2% защита' WHERE special_effect = '-2% DEF';
UPDATE items SET special_effect = '+5% блок' WHERE special_effect = '+5% block';
UPDATE items SET special_effect = 'Игнор защиты' WHERE special_effect = 'ignore defense';
UPDATE items SET special_effect = 'Урон при низком HP' WHERE special_effect = 'low_hp_damage';
UPDATE items SET special_effect = 'Контратака' WHERE special_effect = 'counter_attack';
UPDATE items SET special_effect = 'Уклонение после защиты' WHERE special_effect = 'defend_dodge';
UPDATE items SET special_effect = 'Предупреждение о способности' WHERE special_effect = 'warn_ability';
UPDATE items SET special_effect = 'Урон элитам' WHERE special_effect = 'elite_damage';
UPDATE items SET special_effect = 'Казнь' WHERE special_effect = 'execute_damage';
UPDATE items SET special_effect = 'Атака после защиты' WHERE special_effect = 'after_defend_attack';
UPDATE items SET special_effect = 'Атака при низком HP' WHERE special_effect = 'low_hp_attack';
UPDATE items SET special_effect = 'Критический ожог' WHERE special_effect = 'critical_burn';
UPDATE items SET special_effect = 'Усиление при убийстве' WHERE special_effect = 'kill_next_attack';
UPDATE items SET special_effect = 'Урон при предсказании' WHERE special_effect = 'predicted_damage';
UPDATE items SET special_effect = 'Сила способностей' WHERE special_effect = 'ability_power';
UPDATE items SET special_effect = 'Блок' WHERE special_effect = 'block';
UPDATE items SET special_effect = 'Отражение урона' WHERE special_effect = 'reflect_damage';
UPDATE items SET special_effect = 'Идеальный блок' WHERE special_effect = 'perfect_block';
UPDATE items SET special_effect = 'Контр после защиты' WHERE special_effect = 'guard_counter';
UPDATE items SET special_effect = 'Блок способности' WHERE special_effect = 'ability_block';
UPDATE items SET special_effect = 'Снижение урона' WHERE special_effect = 'damage_reduction';
UPDATE items SET special_effect = 'Регенерация при атаке' WHERE special_effect = 'attack_regeneration';
UPDATE items SET special_effect = 'Сопротивление эффектам' WHERE special_effect = 'status_resistance';
UPDATE items SET special_effect = 'Аварийный щит' WHERE special_effect = 'emergency_shield';
UPDATE items SET special_effect = 'Длительность дебафов' WHERE special_effect = 'debuff_duration';
UPDATE items SET special_effect = 'Восстановление' WHERE special_effect = 'recovery';
UPDATE items SET special_effect = 'Сопротивление заморозке' WHERE special_effect = 'freeze_resistance';
UPDATE items SET special_effect = 'Уклонение от способностей' WHERE special_effect = 'ability_evasion';
UPDATE items SET special_effect = 'Уклонение от кулдауна' WHERE special_effect = 'cooldown_evasion';
UPDATE items SET special_effect = 'Регенерация' WHERE special_effect = 'regeneration';
UPDATE items SET special_effect = 'Воскрешение' WHERE special_effect = 'revive';
UPDATE items SET special_effect = 'Снижение первого удара' WHERE special_effect = 'first_hit_reduction';
UPDATE items SET special_effect = 'Скрытие последнего действия' WHERE special_effect = 'hide_last_action';
UPDATE items SET special_effect = 'Крит при низком HP' WHERE special_effect = 'low_hp_crit';
UPDATE items SET special_effect = 'Урон в атаку' WHERE special_effect = 'damage_to_attack';
UPDATE items SET special_effect = 'Жадность' WHERE special_effect = 'greed';
UPDATE items SET special_effect = 'Дополнительное действие' WHERE special_effect = 'extra_action';
UPDATE items SET special_effect = 'Атака от потери HP' WHERE special_effect = 'lost_hp_attack';
UPDATE items SET special_effect = 'Меняющийся бонус' WHERE special_effect = 'changing_bonus';
UPDATE items SET special_effect = 'Уникальный' WHERE special_effect = 'unique';
UPDATE items SET special_effect = '-5% восстановление' WHERE special_effect = '-5% recovery';

COMMENT ON COLUMN items.special_effect IS 'Специальный эффект предмета (на русском языке)';
